### ISSUE TITLE
Prepare `conda-libmamba-solver 23.1.0` release 

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-libmamba-solver#124]
### Summary

Placeholder for `conda-libmamba-solver 23.1.0` release.

### Tasks

[milestone]: https://github.com/conda/conda-libmamba-solver/milestone/2
[releases]: https://github.com/conda/conda-libmamba-solver/releases
[main]: https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock/pull/8
[conda-forge]: https://github.com/conda-forge/conda-libmamba-solver-feedstock

- [x] [Complete outstanding PRs][milestone]
- [x] Create release PR (https://github.com/conda/conda-libmamba-solver/pull/125)
    - See release process https://github.com/conda/infra/issues/541
- [x] [Publish Release][releases]
  - https://github.com/conda/conda-libmamba-solver/releases/tag/23.1.0 
- [X] [Create/update `23.1.x` branch](https://github.com/conda/conda-libmamba-solver/tree/23.1.x)
- [ ] Feedstocks
    - [x] Bump version [Anaconda's main][main] - https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock/pull/8
    - [x] Bump version [conda-forge][conda-forge] - https://github.com/conda-forge/conda-libmamba-solver-feedstock/pull/11
    - [ ] Link any other feedstock PRs that are necessary
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - [ ] Element
    - [ ] Twitter

**Comment by dholth** [comment]
https://github.com/conda/conda-libmamba-solver/issues/132

**Comment by jaimergp** [comment]
https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock/pull/8 is merged. Closing!

**Comment by jezdez** [comment]
@jaimergp was this announced though?

**Comment by jaimergp** [comment]
I think Dave's announcement included it, yes!
