### ISSUE TITLE
Release 23.3.0

### ISSUE THREAD

**Issue by jezdez** [conda/conda-libmamba-solver#168]
### Summary

Placeholder for `conda-libmamba-solver 23.3.0` release.

### Tasks

[milestone]: https://github.com/conda/conda-libmamba-solver/milestone/4
[releases]: https://github.com/conda/conda-libmamba-solver/releases
[main]: https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock
[conda-forge]: https://github.com/conda-forge/conda-libmamba-solver-feedstock

- [ ] [Complete outstanding PRs][milestone]
- [ ] Create release PR
    - See release process https://github.com/conda/infra/issues/541
- [ ] [Publish Release][releases]
- [ ] Create/update `23.3.x` branch
- [ ] Feedstocks
    - [ ] Bump version [Anaconda's main][main]
    - [ ] Bump version [conda-forge][conda-forge]
    - Link any other feedstock PRs that are necessary
- [ ] Hand off to the Anaconda packaging team
- [ ] Announce release
    - [ ] Slack
    - [ ] Twitter
