### ISSUE TITLE
Known solver differences

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-libmamba-solver#198]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

This epic compiles all reported examples of known solver differences between `conda-libmamba-solver` and `classic`. Please check if your issue can be explained by the [documented use cases](#TBA) or any of the listed issues below.

### Linked Issues & PRs

- [ ] Old `pydantic` version chosen: https://github.com/conda/conda-libmamba-solver/issues/115
- [ ] https://github.com/conda/conda-libmamba-solver/issues/131

**Comment by jezdez** [comment]
Also see #227

**Comment by agriyakhetarpal** [comment]
#741 updates the difference noted in #131, indicating it is no longer valid.

**Comment by jaimergp** [comment]
Turns out #131 still applies. See https://github.com/conda/conda-libmamba-solver/pull/814.
