### ISSUE TITLE
Release 23.5.0

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-libmamba-solver#203]
### Summary

Placeholder for `conda-libmamba-solver 23.5.0` release.

| Pilot | @jaimergp |
|---|---|
| Co-pilot | @costrouc  |

### Tasks

[milestone]: https://github.com/conda/conda-libmamba-solver/milestone/5
[process]: https://github.com/conda/conda-libmamba-solver/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-libmamba-solver/releases
[main]: https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock
[conda-forge]: https://github.com/conda-forge/conda-libmamba-solver-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-libmamba-solver/
[announcement]: https://github.com/conda/communications

#### The week before release week

- [x] Create release branch (named `23.5.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/23.5.x`)
- [x] [Complete outstanding milestone items][milestone]
- [x] Test release candidates
    

#### Release week

- [X] Create release PR (see [release process][process]) https://github.com/conda/conda-libmamba-solver/pull/212
- [x] [Publish release](https://github.com/conda/conda-libmamba-solver/releases/tag/23.5.0)
- [ ] Merge release branch back into main - https://github.com/conda/conda-libmamba-solver/pull/213
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock/pull/11
    - [x] https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock/pull/12
    - [x] https://github.com/conda-forge/conda-libmamba-solver-feedstock/pull/14
    
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - [x] Create release [announcement draft][announcement]
    - [x] Discourse
    - [x] Twitter
    - [x] Matrix

**Comment by jaimergp** [comment]
Tested [`conda-canary/label/dev` artifacts](https://anaconda.org/conda-canary/conda-libmamba-solver/files) locally on the Docker image we use in CI:

```
$ conda install -n base -c conda-canary/label/dev conda conda-libmamba-solver
```

Then I ran these commands:

```
$ conda create -n unused --dry-run python
$ conda create -n unused --dry-run python --solver libmamba
$ conda create -n unused --dry-run python --solver libmamba --experimental jlap
```

All work as expected.

I also checked if `conda-libmamba-solver 23.3` is compatible with `conda 23.5` and found no issues with the commands above.

@jezdez reported ✅ for Windows.
