### ISSUE TITLE
Release 23.7.0

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-libmamba-solver#236]
### Summary

Placeholder for `conda-libmamba-solver 23.7.0` release.

| Pilot | @jaimergp |
|---|---|
| Co-pilot | @costrouc  |

### Tasks

[milestone]: https://github.com/conda/conda-libmamba-solver/milestone/6
[process]: https://github.com/conda/conda-libmamba-solver/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-libmamba-solver/releases
[main]: https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock
[conda-forge]: https://github.com/conda-forge/conda-libmamba-solver-feedstock

#### The week before release week

- [X] [Complete outstanding PRs][milestone]
- [ ] Test release candidates
    

#### Release week

- [X] Create release PR (see [release process][process]) https://github.com/conda/conda-libmamba-solver/pull/251
- [x] [Publish release][releases]
- [x] Feedstocks
    - [x] Bump version & update dependencies/tests in [Anaconda, Inc.'s feedstock][main] - https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock/pull/13
    - [x] Bump version & update dependencies/tests in [conda-forge feedstock][conda-forge] - https://github.com/conda-forge/conda-libmamba-solver-feedstock/pull/15
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [ ] conda.org (link to pull request)
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [x] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)
