### ISSUE TITLE
Release 23.9.x

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-libmamba-solver#277]
### Summary

Placeholder for `conda-libmamba-solver 23.9.x` release.

| Pilot | @jaimergp |
|---|---|
| Co-pilot | @costrouc |

### Tasks

[milestone]: https://github.com/conda/conda-libmamba-solver/milestone/7
[process]: https://github.com/conda/conda-libmamba-solver/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-libmamba-solver/releases
[main]: https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock
[conda-forge]: https://github.com/conda-forge/conda-libmamba-solver-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-libmamba-solver/

#### The week before release week

- [x] Ensure release candidates are being successfully built (see `conda-canary/label/dev`)
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    - @jaimergp and @costrouc: [QA notes](https://hackmd.io/GdQoVv3ZSNCj_na6UBJE2A)

Given how this is the first version that might be default in conda, we are also testing some other things in the satellite ecosystems. These are nice-to-have:

- [ ] https://github.com/conda/conda/pull/12984
- [ ] https://github.com/conda-incubator/setup-miniconda/pull/291
- [ ] https://github.com/conda-forge/libarchive-feedstock/issues/69
- [ ] https://github.com/conda-forge/conda-forge.github.io/issues/2006

#### Release week

- [X] Create release PR (see [release process][process]) - https://github.com/conda/conda-libmamba-solver/pull/299
- [x] [Publish release][releases]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock/pull/14
    - [X] https://github.com/conda-forge/conda-libmamba-solver-feedstock/pull/16
    - [X] https://github.com/conda-forge/conda-libmamba-solver-feedstock/pull/17
    
- [X] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [ ] conda.org (link to pull request)
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

**Comment by jaimergp** [comment]
Note we are receiving some reports and we'll issue a 23.9.1 hotfix soon:

- [ ] https://github.com/conda/conda-libmamba-solver/pull/302
- [ ] https://github.com/conda/conda-libmamba-solver/issues/303
