### ISSUE TITLE
Release 23.11.x

### ISSUE THREAD

**Issue by jezdez** [conda/conda-libmamba-solver#350]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

Placeholder for `conda-libmamba-solver 23.11.x` release.

| Pilot | @jezdez |
|---|---|
| Co-pilot | @jaimergp |

### Tasks

[milestone]: https://github.com/conda/conda-libmamba-solver/milestone/8
[process]: https://github.com/conda/conda-libmamba-solver/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-libmamba-solver/releases
[main]: https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock
[conda-forge]: https://github.com/conda-forge/conda-libmamba-solver-feedstock

#### The week before release week

- [x] Create release branch (named `23.11.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-libmamba-solver-23.11.x`) -- used equivalent `23.9.3.8`: [noarch/conda-libmamba-solver-23.9.3.8_g33e33e6-py_0.tar.bz2](https://anaconda.org/conda-canary/conda-libmamba-solver/23.9.3.8_g33e33e6/download/noarch/conda-libmamba-solver-23.9.3.8_g33e33e6-py_0.tar.bz2)
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    - Signed off by @jaimergp. See comment below.

#### Release week

- [x] Create release PR (see [release process][process]) - https://github.com/conda/conda-libmamba-solver/pull/353
- [x] [Publish release][releases] https://github.com/conda/conda-libmamba-solver/releases/tag/23.11.0
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock/pull/17
    - [x] https://github.com/conda-forge/conda-libmamba-solver-feedstock/pull/21
    
- [x] Hand off to the Anaconda packaging team
- [x] Create release PR (see [release process][process]) - https://github.com/conda/conda-libmamba-solver/pull/384
- [x] [Publish release][releases] https://github.com/conda/conda-libmamba-solver/releases/tag/23.11.1
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock/pull/18
    - [x] https://github.com/conda-forge/conda-libmamba-solver-feedstock/pull/22
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [ ] conda.org (link to pull request)
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

### Linked Issues & PRs

Refs https://github.com/conda/conda/issues/13156

**Comment by jaimergp** [comment]
Played a bit with [noarch/conda-libmamba-solver-23.9.3.8_g33e33e6-py_0.tar.bz2](https://anaconda.org/conda-canary/conda-libmamba-solver/23.9.3.8_g33e33e6/download/noarch/conda-libmamba-solver-23.9.3.8_g33e33e6-py_0.tar.bz2) in my own `base` environment and basic stuff seems to work:

```
$ conda install conda-canary/label/dev::conda-libmamba-solver=23.9.3.8 --no-deps
Channels:
 - conda-forge
 - conda-canary/label/dev
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: | warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested conda-canary/label/dev::conda-libmamba-solver =23.9.3.8*
  - cannot install both pin-1-1 and pin-1-1

Could not solve for environment specs
The following packages are incompatible
├─ conda-libmamba-solver 23.9.3.8*  does not exist (perhaps a typo or a missing channel);
└─ pin-1 is installable with the potential options
   ├─ pin-1 1, which can be installed;
   └─ pin-1 1 conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.9.* (labeled as 'pin-1')
```
^ The channel spec gets added with lower priority than the configured channels so it's expected that we can't install it strict channel priority. This might be something to look at in the future (adding channels from specs with higher priority that configured values), but this is our current behaviour and the solver responds to that.

If we use flexible channel priority, everything is good:

```
$ CONDA_CHANNEL_PRIORITY=flexible conda install conda-canary/label/dev::conda-libmamba-solver=23.9.3.8 --no-deps
Channels:
 - conda-forge
 - conda-canary/label/dev
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/jrodriguez/.local/anaconda

  added / updated specs:
    - conda-canary/label/dev::conda-libmamba-solver=23.9.3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-libmamba-solver-23.9.3.8_g33e33e6|             py_0          41 KB  conda-canary/label/dev
    ------------------------------------------------------------
                                           Total:          41 KB

The following packages will be UPDATED:

  conda-libmamba-so~                 23.9.3.6_g27d164c-py_0 --> 23.9.3.8_g33e33e6-py_0 


Proceed ([y]/n)? 


Downloading and Extracting Packages:
                                                                                                                                                             
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

`23.9.3.8` is current main aka 23.11rc1. 

I can `Ctrl-C` in metadata collection and solving stages:

```
$ conda install --dry-run vaex
Channels:
 - conda-forge
 - conda-canary/label/dev
Platform: osx-arm64
Collecting package metadata (repodata.json): - failed

CondaError: KeyboardInterrupt
```

```
$ conda install --dry-run vaex
Channels:
 - conda-forge
 - conda-canary/label/dev
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: / failed

CondaError: KeyboardInterrupt
```

The "remove because unavailable" problem is also gone. In a fresh env with Python 3.11 and numpy:

```
$ conda install python=3.12 --override-channels -c defaults
Channels:
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package numpy-1.26.0-py311hb8f3215_0 requires python_abi 3.11.* *_cp311, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ numpy is installable with the potential options
│  ├─ numpy 1.26.0 would require
│  │  └─ python_abi 3.11.* *_cp311, which requires
│  │     └─ python 3.11.* *_cpython, which can be installed;
│  ├─ numpy [1.19.2|1.19.5|...|1.24.3] would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  ├─ numpy [1.19.2|1.19.5|...|1.26.0] would require
│  │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│  ├─ numpy [1.21.2|1.21.5|...|1.26.0] would require
│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  └─ numpy [1.22.3|1.23.5|...|1.26.0] would require
│     └─ python >=3.11,<3.12.0a0 , which can be installed;
└─ python 3.12**  is not installable because it conflicts with any installable versions previously reported.
```

I think we are GO to cut the release!

**Comment by jezdez** [comment]
Reopening for 23.11.1
