### ISSUE TITLE
Release 23.12.x

### ISSUE THREAD

**Issue by jezdez** [conda/conda-libmamba-solver#400]
### Summary

Placeholder for `conda-libmamba-solver 23.12.x` release.

| Pilot | @jezdez |
|---|---|
| Co-pilot | @jaimergp |

### Tasks

[milestone]: https://github.com/conda/conda-libmamba-solver/milestone/9
[process]: https://github.com/conda/conda-libmamba-solver/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-libmamba-solver/releases
[main]: https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock
[conda-forge]: https://github.com/conda-forge/conda-libmamba-solver-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-libmamba-solver/

#### The week before release week

- [x] Create release branch (named `23.12.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-libmamba-solver-23.12.x`)
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    

#### Release week

- [x] Create release PR https://github.com/conda/conda-libmamba-solver/pull/407
- [x] [Publish release][releases] https://github.com/conda/conda-libmamba-solver/releases/tag/23.12.0
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock/pull/19
    - [x] https://github.com/conda-forge/conda-libmamba-solver-feedstock/pull/23
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [ ] conda.org (link to pull request)
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

**Comment by jaimergp** [comment]
I think we are fine here now and can close.
