### ISSUE TITLE
Release 22.12.0

### ISSUE THREAD

**Issue by jezdez** [conda/conda-libmamba-solver#88]
### Summary

Placeholder for `conda-libmamba-solver 22.12.0` release.

### Tasks

[milestone]: https://github.com/conda/conda-libmamba-solver/milestone/1
[releases]: https://github.com/conda/conda-libmamba-solver/releases
[main]: https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock
[conda-forge]: https://github.com/conda-forge/conda-libmamba-solver-feedstock

- [x] [Complete outstanding PRs][milestone]
- [x] Create release PR: https://github.com/conda/conda-libmamba-solver/pull/85
    - See release process https://github.com/conda/infra/issues/541
- [x] [Publish Release][releases]
- [x] Create/update `YY.M.x` branch
- [x] Feedstocks
    - [x] Bump version [Anaconda's main][main]: https://github.com/AnacondaRecipes/conda-libmamba-solver-feedstock/pull/7
    - [x] Bump version [conda-forge][conda-forge]: https://github.com/conda-forge/conda-libmamba-solver-feedstock/pull/8
    - Link any other feedstock PRs that are necessary
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - [ ] Slack
    - [ ] Twitter
